name: Check supply chain security issues
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  run_macaron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Run Macaron action
        uses: behnazh/test-macaron-action@91d03088c2d207725151c20bff6976eaabc0cffd
        with:
          repo_path: ./
          policy_file: check-github-actions
          policy_purl: 'pkg:github.com/Demolus13/dummy@.*'
          upload_attestation: true
          subject_path: ./output/vsa.intoto.jsonl
